-- This schema is generated based on the current DBContext. Please check the class Seeder to see.
CREATE TABLE sensor_data (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    timestamp timestamp with time zone NOT NULL,
    temperature double precision NOT NULL,
    humidity double precision NOT NULL,
    soil double precision NOT NULL,
    window_status text NOT NULL,
    CONSTRAINT "PK_sensor_data" PRIMARY KEY (id)
);


CREATE TABLE thresholds (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    templow real NOT NULL,
    temphigh real NOT NULL,
    humiditylow real NOT NULL,
    humidityhigh real NOT NULL,
    CONSTRAINT "PK_thresholds" PRIMARY KEY (id)
);


CREATE TABLE "user" (
    id text NOT NULL,
    email text NOT NULL,
    hash text NOT NULL,
    salt text NOT NULL,
    role text NOT NULL,
    CONSTRAINT user_pkey PRIMARY KEY (id)
);


